config/routes.rb
WhatsThePlan::Application.routes.draw do
  devise_for :users
  resources :users, :only => [:show]
  resources :plans, :only => [:new, :create, :index, :show]
  root :to     => 'plans#index'
  post '/yelp' => 'yelp_queries#create'
  get 'plans/:id/refresh' => 'plans#refresh'
  match '*path' => 'not_found#show'
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  NEARBY_PLANS = 8
  attr_accessible :start_date, :end_date, :title, :city, :sequenced, :activities_attributes,
                  :best_route_ids
  serialize :best_route_ids

  validates :title, :presence => true
  validate  :end_date_before_start_date

  belongs_to :user
  has_many :activity_plans
  has_many :activities, :through => :activity_plans, :inverse_of => :plans
  accepts_nested_attributes_for :activities

  before_validation :default_dates, :unless => Proc.new { self.start_date }
  after_create :create_sequence

  def self.nearby_plans(plan)
    Plan.where(:city => plan.city).where("id != ?", plan.id).last(NEARBY_PLANS)
  end

  def best_route
    self.best_route_ids.map do |id|
      best_activities.find { |activity| activity.id == id } if id
    end
  end

  private
  def create_sequence
    PlanWorker.perform_async(self.id)
  end

  def end_date_before_start_date
    if self.end_date && self.start_date && self.end_date < self.start_date
      errors.add(:start_date, "End date cannot be earlier than start date")
    end
  end

  def default_dates
    self.start_date = Date.today
    self.end_date = Date.tomorrow
  end

  def best_activities
    Activity.find(self.best_route_ids)
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController

  def index
    @plans = Plan.all
  end

  def new
    @plan = Plan.new
    @plan.activities.build
  end

  def create
    @plan = Plan.new(params[:plan])
    @plan.user = current_user if current_user

    if @plan.save
      render :json => { plan: @plan }
    else
      render :json => { plan: @plan, activities: @plan.activities }
    end
  end

  def show
    @plan = Plan.find(params[:id])
    if @plan && @plan.sequenced
      @best_route = @plan.best_route
      @nearby_plans = Plan.nearby_plans(@plan)
    else
      render 'processing'
    end
  end

  def refresh
    @plan = Plan.find(params[:id])
    render :json => { :sequenced => @plan && @plan.sequenced }
  end
end

app/helpers/plans_helper.rb
module PlansHelper

  def time_slot_title(index)
    ["MORNING ACTIVITY (9am - Noon)", "LUNCH",
     "AFTERNOON ACTIVITY (1:30pm - 5:00pm)", "DINNER"][index]
  end

  def title(activity)
    activity ? activity.title : "Placeholder"
  end

  def street(activity)
    activity.street
  end

  def city_state(activity)
    "#{activity.city}, #{activity.state} #{activity.zip_code}"
  end

  def map(best_route)
    best_route = best_route.delete_if { |activity| activity.nil? }

    gmaps({ "direction" =>
            { "data"      =>
              { "from" => best_route.first.gmaps_string,
                "to"   => best_route.last.gmaps_string},
                "options" => {"waypoints" => waypoints(best_route), "travelMode" => "DRIVING",
                              "avoidHighways" => TRUE} }
          })
  end

  def user_map(user)
    cities = []
    user.plans.each do |plan|
      cities << plan.city
    end

  end

  def waypoints(best_route)
    waypoints = best_route[1..-2].map do |activity|
      activity.gmaps_string
    end
  end

  def distances_between_activities(best_route)
    coords = coordinates(best_route.include?(nil) ? best_route.compact : best_route )
    distances = []
    (coords.length - 1).times do |i|
      distances << (distance_between(coords[i], coords[i+1]) * 1.2).round(1)
    end
    distances
  end

  def coordinates(route)
    route.map { |activity| activity.to_coordinates }
  end

  def distance_between(from, to)
    Geocoder::Calculations.distance_between(from, to)
  end
end

app/views/plans/_activity.html.erb
<div class="span6 plan-activity-block">
  <h3 class="time-slot-title"><%= time_slot_title(index) %></h3>
  <div class="plan-activity-image">
    <%= image_tag(activity.image_url, :size => '80x80') %>
  </div>
  <div class="plan-activity-details">
    <h3><%= title(activity) %></h3>
    <p class="street-add"><%= street(activity) %></p>
    <p class="city-add"><%= city_state(activity) %></p>
  </div>
  <div class="distance">
    <% dist = distances_between_activities(@best_route) %>
    <% unless @best_route[index+1].nil? %>
      <div class="distance">~<%= dist[index] %> mi <i class="icon-arrow-down"></i></div>
    <% end %>
  </div>
</div>

app/views/plans/_demo.html.erb
<div class="demo">
  <div class="clear">
    <div class="demo-title">
      <h2>Let's Make A Plan! (How this Thing Works)</h2>
    </div>
    <div class="steps">
      <h3>Find Things To Do</h3>
        <p>Search for Activities</p>
        <p>Search for Restaurants</p>
    </div>
    <div class="steps">
      <h3>Add Favorite Activities</h3>
        <p>Don't Forget to Add a few Meals</p>
        <p>Add Custom Destinations</p>
    </div>
    <div class="steps">
      <h3>We Do The Rest!</h3>
      <p>Activities Organized by Type</p>
      <p>Route Based on Min. Distance</p>
    </div>
  </div>
</div>

app/views/plans/_placeholder.html.erb
<div class="span6 plan-activity-block">
  <h3 class="time-slot-title"><%= time_slot_title(index) %></h3>
  <div class="plan-activity-image">
    <% if (index % 2).zero? %>
      <%= image_tag('hiking.png', :size => "80x80") %>
    <% else %>
      <%= image_tag('knife-fork-plate.png', :size => "80x80") %>
    <% end %>
  </div>
  <div class="plan-activity-details">
    <% if (index % 2).zero? %>
      <h3>Open Time Slot - Do Something Fun!</h3>
      <p class="city-add"><%= @plan.city %></p>
    <% else %>
      <h3>Open Time Slot - Don't Forget to Eat!</h3>
      <p class="city-add"><%= @plan.city %></p>
    <% end %>
  </div>
</div>

app/views/plans/_processing.html.erb
<h1 id='processing'>Calculating best route! Page will load in a few seconds.</h1>

app/views/plans/_sequenced_plan.html.erb
<div class="plan-block">
  <div class="activities">
    <% @best_route.each_with_index do |activity, index| %>
      <% if activity %>
        <%= render 'activity', :activity => activity, :index => index %>
      <% else %>
        <%= render 'placeholder', :index => index %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="side-bar">
  <div class="show-map">
    <h4>Map out your activities</h4>
    <%= map(@best_route) %>
  </div>

  <div class="other-plans">
    <h4>Other nearby plans</h4>
      <div>
        <ul>
          <% @nearby_plans.each do |plan| %>
            <li><%= link_to "#{plan.title} (#{plan.city})", plan_path(plan) %></li>
          <% end %>
        </ul>
      </div>
  </div>
</div>

app/views/plans/index.html.erb
<div class="source-image"></div>

<div id="left-side"></div>
<i class="icon-angle-left icon-x" ></i>

<div id="right-side"></div>
<i class="icon-angle-right icon-x" ></i>

  <h1 class="home-header">Welcome to What's the Plan?<br>
       Spend less time planning and more time enjoying yourself!</h1>

  <div class="listofplans">
    
  
  </div>

app/views/plans/new.html.erb
<h1 class="page-title">Select activities for your next plan</h1>
<form class="plan-create">
  <div class="activity-form">
      <input id="destination" class="input-field" name="destination" placeholder="Activity name (e.g. Coit Tower, mexican food)"
             type="text" />
      <input id="address" class="input-field" name="address" placeholder="Location (e.g. SF, Paris, Berlin)" type="text"/>

    <div class='activity-options'>
      <input id="meal" name="meal" type="checkbox" />Is this a restaurant?
      <input class="btn btn-primary add-activity" name="commit" type="submit" value="Search for activities" />
    </div>
  </div>

  <div class="plan-builder">
    <div class="new-plan">
      <h3>My Plan's Activities</h3>
      <div class="plan-creation">
        <input id="title" class="plan-title-field" name="title" placeholder="Plan title (e.g. My day in Paris)" type="text"/>
        <input class="btn btn-primary create-plan disabled" name="commit" type="submit" value="Create my plan!" />
      </div>
    </div>

    <div class="search-results">
      <h3>Search Results</h3>
    </div>
  </div>
</form>

<%= render 'demo' %>

app/views/plans/processing.html.erb
<div class='plan-title'>
  <div class='title'>
    <h1><%= @plan.title %></h1>
  </div>
</div>

<%= render 'processing' %>

app/views/plans/show.html.erb
<div class='plan-title'>
  <div class='title'>
    <h1><%= @plan.title %></h1>
  </div>
</div>

<%= render 'sequenced_plan' %>