config/routes.rb
WhatsThePlan::Application.routes.draw do
  devise_for :users
  resources :users, :only => [:show]
  resources :plans, :only => [:new, :create, :index, :show]
  root :to     => 'plans#index'
  post '/yelp' => 'yelp_queries#create'
  get 'plans/:id/refresh' => 'plans#refresh'
  match '*path' => 'not_found#show'
end

app/views/layouts/_header.html.erb
<div class='navbar navbar-fixed-top navbar-inverse'>
  <div class='navbar-inner'>
    <div class='container'>
    <ul class='nav'>
      <li id="appname"><%= link_to "What's the Plan?", root_path, class: "brand" %></li>
      <% if current_user %>
        <li><%= link_to "Your Profile", user_path(current_user) %></li>
      <% end %>
      <li><%= link_to "Create a plan!", new_plan_path %></li>
    </ul>
    <ul class='nav pull-right'>
      <% if current_user %>
        <li><%= link_to 'Log Out', destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to 'Sign Up', new_user_registration_path, class: "show-signup" %></li>
        <li><%= link_to 'Sign In', new_user_session_path , class: "show-signin" %>  </li>
      <% end %>
    </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Alegreya+SC' rel='stylesheet' type='text/css'> <!-- mushi -->
  <link href='http://fonts.googleapis.com/css?family=Fjalla+One' rel='stylesheet' type='text/css'>
  <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?v=3&sensor=true"></script>

  <title>WhatsThePlan</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render :partial => 'layouts/header' %>
  <div class='container'>
    <%= yield %>
  </div>
</body>
<%= yield :scripts %>
</html>

app/views/layouts/not_found.html.erb
<img src="https://s3.amazonaws.com/forapp/404-color.png">